apiVersion: v1
kind: Service
metadata:
  name: bootcamp-api
  namespace: steeltoek8s
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    run: bootcamp-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
